### ISSUE TITLE
Confusing Documentation for Time Types

### ISSUE THREAD

**Issue by thaddeusdiamond** [Hyperion-BT/Helios-Book#3]
This is about the section on "Time Types": https://hyperion-bt.github.io/Helios-Book/helios_builtins/time_types.html

The bottom methods section of `TimeRange` reads:
```
// @returns 'true' if 'time' is before start of 'self'
func is_before(self, time: Time) -> Bool

// @returns 'true' if 'time' is after end of 'self'
func is_after(self, time: Time) -> Bool
```

However, this makes it appear as if this method returns true if the `time` object being passed in is before or after the time range.  The real behavior of the function is the inverse.  The first method returns true if the `time_range` object *is before `time`*.  Same thing with *after* for the second function.  Please update this.

**Comment by christianschmitz** [comment]
Fixed now.

Sorry about this, probably wasn't thinking when I wrote those two comments in the docs.

Thanks for your patience!
