### ISSUE TITLE
Discord link invalid. Invite?

### ISSUE THREAD

**Issue by jackdarrylfraser** [Hyperion-BT/Helios-Book#5]
https://github.com/Hyperion-BT/Helios-Book/blob/371dfcded4e5b430ea16d6fa3e8b6d44375c004c/README.md?plain=1#L5

<img width="456" alt="Screen Shot 2022-11-21 at 11 46 38 AM" src="https://user-images.githubusercontent.com/95544241/203125017-b440ec11-fdf8-4052-9299-08376087e3fe.png">

The discord link in the readme description is invalid. When I go to https://discord.gg/2hT2QFvj I get the above message form discord.

**Comment by christianschmitz** [comment]
Oops, old link, will update

**Comment by christianschmitz** [comment]
fixed now.

Thanks for pointing this out!
